"""
backends/tabular.py
-------------------
SQLite-based structured memory backend.

In a real system, this would connect to PostgreSQL with pgvector
or a time-series database like TimescaleDB.

This uses an in-memory SQLite database seeded with example
user order data.
"""

import sqlite3

# Initialise in-memory SQLite database
_conn = sqlite3.connect(":memory:", check_same_thread=False)
_cursor = _conn.cursor()

# Create and seed the orders table
_cursor.executescript("""
CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    product TEXT,
    amount_inr INTEGER,
    order_date TEXT
);

INSERT INTO orders VALUES
(1, 42, 'Python AI Course', 2999, '2026-04-10');

INSERT INTO orders VALUES
(2, 42, 'LangChain Guide PDF', 499, '2026-04-22');

INSERT INTO orders VALUES
(3, 99, 'RAG Masterclass', 1499, '2026-03-15');
""")

_conn.commit()


def query_tabular(user_query: str) -> str:
    """
    Simplified tabular lookup.

    In production, the SQL would be generated by an LLM
    (Text-to-SQL pattern).

    Here we use keyword matching to select a pre-written
    query for clarity.
    """

    q = user_query.lower()

    # Query orders for User 42
    if "user 42" in q or "user42" in q:

        _cursor.execute(
            "SELECT product, amount_inr, order_date FROM orders WHERE user_id = 42"
        )

        rows = _cursor.fetchall()

        if not rows:
            return "No orders found for user 42."

        lines = [
            f"• {product} - ₹{amount} on {date}"
            for product, amount, date in rows
        ]

        return "Orders for user 42:\n" + "\n".join(lines)

    # Query total revenue
    if "total revenue" in q or "all orders" in q:

        _cursor.execute("SELECT SUM(amount_inr) FROM orders")

        total = _cursor.fetchone()[0]

        return f"Total revenue across all orders: ₹{total}"

    return "Could not match the query to a known structured lookup pattern."