apiVersion: v1
kind: Service

metadata:
  name: ai-memory-router-service

spec:
  type: NodePort

  selector:
    app: ai-memory-router

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080